---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: integral-systems-website-frontend-cert
  namespace: integral-systems
spec:
  commonName: integral-systems.ch
  dnsNames:
  - integral-systems.ch
  - www.integral-systems.ch
  - integral-design.ch
  - www.integral-design.ch
  duration: 2160h
  isCA: false
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-http-prod
  privateKey:
    algorithm: ECDSA
    encoding: PKCS1
    size: 384
  renewBefore: 1080h
  secretName: integral-systems-website-frontend-cert
