---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: integral-systems-website-frontend-cert
  namespace: integral-systems
spec:
  commonName: integral-systems.ch
  dnsNames:
  - integral-systems.ch
  - www.integral-systems.ch
  - integral-design.ch
  - www.integral-design.ch
  duration: 2160h
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-http-prod
  keyAlgorithm: ecdsa
  keySize: 384
  renewBefore: 1080h
  secretName: integral-systems-website-frontend-cert
