---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: integral-systems-website-frontend-redirect
  namespace: integral-systems
spec:
  redirectScheme:
    permanent: true
    scheme: https
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: integral-systems-website-frontend-compress
  namespace: integral-systems
spec:
  compress: {}
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: integral-systems-website-frontend-redirectregex
  namespace: integral-systems
spec:
  redirectRegex:
    permanent: true
    regex: ^http://.*?[a-z].*/|^https://[^www][a-z].*/(.*)
    replacement: https://www.integral-systems.ch/$1
