# kubetpl:syntax:$
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: errorhandler
  name: errorhandler
  namespace: integral-systems
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: errorhandler
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: errorhandler
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: class
                operator: In
                values:
                - core
      containers:
      - env:
        - name: TZ
          value: Europe/Zurich
        - name: EMAIL
        image: registry.integral-systems.ch/integral-systems/nginx:stable
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 3
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 1
        name: errorhandler
        ports:
        - containerPort: 3000
          name: 80tcp02
          protocol: TCP
        readinessProbe:
          failureThreshold: 60
          httpGet:
            path: /
            port: 3000
            scheme: HTTP
          initialDelaySeconds: 20
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 50m
            memory: 50Mi
          requests:
            cpu: 5m
            memory: 7Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - CHOWN
            - SETGID
            - SETUID
            drop:
            - ALL
          privileged: false
          procMount: Default
          readOnlyRootFilesystem: false
          runAsNonRoot: true
      imagePullSecrets:
      - name: fx-docker-registry
      nodeSelector:
        class: core
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 777
        runAsGroup: 777
        runAsUser: 9988
      terminationGracePeriodSeconds: 30
