---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: ersterstck-website-cert
  namespace: kulturverein-walzwerk
spec:
  commonName: ersterstock.ch
  dnsNames:
  - ersterstock.ch
  - www.ersterstock.ch
  duration: 2160h
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-http-prod
  keyAlgorithm: ecdsa
  keySize: 384
  renewBefore: 1080h
  secretName: ersterstck-website-cert
