# kubetpl:syntax:go-template
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{.PROJECT_NAME}}-cert
  namespace: {{.NAMESPACE}}
spec:
  commonName: {{ .PRIMARY_DOMAIN }}
  secretName: {{ .PROJECT_NAME }}-cert
  dnsNames:
  {{ if .PRIMARY_DOMAIN }}- {{.PRIMARY_DOMAIN }} {{ end }}
  {{ range .DOMAINS }}
  - {{.}}
  {{ end }}
  duration: 2160h #90d
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-http-prod
  isCA: false
  privateKey:
    algorithm: ECDSA
    encoding: PKCS1
    size: 384
  renewBefore: 1080h #30d